export enum Entity {
  UID = 'uid',
  FIRST_NAME = 'firstName',
  LAST_NAME = 'lastName',
  EMAIL = 'email',
  DISPLAY_NAME = 'displayName',
  DATE_OF_BIRTH = 'dob',
  PASSWORD = 'password',
  CONFIRM_PASSWORD = 'confirmPassword',
  IS_DELETED = 'isDeleted',
  IS_CURRENT = 'isCurrent',
  START_DATE = 'startDate',
  END_DATE = 'endDate',
  DESCRIPTION = 'description',
}
